GET http://localhost:8000/api
###
GET http://localhost:8000/api/getTransaction/66f3d25bc4ade2df76f08e3c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmYzYmM0NDlmYTI3NTU1NjE0OTgyMDIiLCJpYXQiOjE3MjcyNTMwMjYsImV4cCI6MTcyNzMzOTQyNiwiYXVkIjoiNjZmM2JjNDQ5ZmEyNzU1NTYxNDk4MjAyIiwiaXNzIjoiRXhwZW5zZSBUcmFja2VyIn0.Vhfru-K3_Sgulrx3jLVi5SRn5AiBovacWyQEvRgMlZ4

###
POST http://localhost:8000/auth/login
Content-Type: application/json
Authorization: Bearer 

{
    "username": "mentorias",
    "password": "15215215a"
}
###
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "username": "mentorias",
    "password": "15215215a",
    "name": "Mentorias"
}
###
POST http://localhost:8000/api/addTransaction
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmZkMGJiZTgxOThkMzk1ZTMzZWU3MWYiLCJpYXQiOjE3Mjk2NjQyOTcsImV4cCI6MTcyOTc1MDY5NywiYXVkIjoiNjZmZDBiYmU4MTk4ZDM5NWUzM2VlNzFmIiwiaXNzIjoiRXhwZW5zZSBUcmFja2VyIn0.kBZQ2_C8l1lL23PT4Vp17v64IUq4dEEvdmDPyRh8QQY
Content-Type: application/json

{
    "title": "Buy milk tea",
    "type": "Income",
    "amount": 25000,
    "date": "09-09-2024",
    "ref": "Buy some milk tea at the supermarket"
}
###

GET http://localhost:8000/api/getTotalIncome
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmZkMGJiZTgxOThkMzk1ZTMzZWU3MWYiLCJpYXQiOjE3Mjk2NjQyOTcsImV4cCI6MTcyOTc1MDY5NywiYXVkIjoiNjZmZDBiYmU4MTk4ZDM5NWUzM2VlNzFmIiwiaXNzIjoiRXhwZW5zZSBUcmFja2VyIn0.kBZQ2_C8l1lL23PT4Vp17v64IUq4dEEvdmDPyRh8QQY
Content-Type: application/json